### PR TITLE
test(app/cypress) set up cypress

### PR DESCRIPTION
**Pull request by geromegrignon**
install cypress
install @cypress/webpack-preprocessor
install ts-loader

create cypress/tsconfig.json
create cypress/plugins/cy-ts-preprocessor.js
update cypress/plugins/index.js

delete e2e folder

change e2e script to cypress open (package.json)
add baseUrl for visit and request cypress methods (cypress.json)

### CODE REVIEW

**Comment by geromegrignon** [comment]
Done!

**Comment by d3lm** [comment]
Thanks for squashing your commits. I left a few comments on our git commit message format in [your other PR](https://github.com/angular-checklist/angular-checklist/pull/22). The same goes for this PR as well. 

Please update the commit message to `test: set up cypress` and also remove the body as it contains the steps as well as the messages from all other commits you had before. The body should be used to add more information and describe how something has changed compared to its previous behavior. Again, for this PR it's pretty obvious what it does.

Sorry for bugging you all the time with this, but we want to embrace the format as much as possible.

Thanks for your understanding and patience!

**Comment by d3lm** [comment]
@geromegrignon Let me know if you need help! I am always happy to assist.

**Comment by geromegrignon** [comment]
Done!

**Comment by geromegrignon** [comment]
I'll take care of both requested changes tonight (EU time).

**Comment by d3lm** [comment]
Thanks @geromegrignon 👍

**Pull request merged**
