### PR TITLE
changed 'is fully' to 'has been completely'

### PR DESCRIPTION
**Pull request by tayambamwanza**
This is my initial pull request, I just changed some text in the readme.

### CODE REVIEW

**Comment by tayambamwanza** [comment]
@d3lm Alright thanks, updated the commit message.

**Comment by d3lm** [comment]
I am actually thinking, this can be merged into master because it has nothing to do with the PWA stuff. Do you mind sending a PR against master and also squash all your commits? I would appreciate that.

**Comment by d3lm** [comment]
Sounds good!

**Comment by tayambamwanza** [comment]
I'll just start over

**Pull request closed without merging**
