### PR TITLE
fix(app): remove unused imports

### PR DESCRIPTION
**Pull request by geromegrignon**

### CODE REVIEW

**Comment by geromegrignon** [comment]
Done!

**Comment by d3lm** [comment]
Cool, now can you please squash all your commits? Thanks :pray:

**Comment by geromegrignon** [comment]
Working on it but having difficulties, it sounds like git commands are messing up because of commitlint

**Comment by geromegrignon** [comment]
Victory!

**Comment by d3lm** [comment]
Not quite yet :D Your commit still has a body, which is not entirely correct. Also the commit meesage is pretty self-explanatory, so I'd say we remove the commit body :P

**Comment by geromegrignon** [comment]
Finally done, sorry for that.

**Pull request merged**
