### PR TITLE
content(rxjs): avoid memory leaks

### PR DESCRIPTION
**Pull request by thekiba**
Use `publishReplay` and `refCount` instead of `shareReplay` to avoid memory leaks.
See https://github.com/ReactiveX/rxjs/issues/3336

### CODE REVIEW

**Comment by KwintenP** [comment]
Hi,

It actually depends on the use case that you have. If you have an http Observable that will just give you one value, than you can perfectly use this. 

If you'd want to change this to something that reflects some nuance on when to use which one, I'm definitely up for it. You can read about it in this article that I wrote: https://blog.strongbrew.io/share-replay-issue/

**Comment by thekiba** [comment]
@KwintenP 
It doesn't matter because:
 — **uses the Observable interface**, hoping for its completion makes the code fragile;
 — **subscription cannot be canceled**, it is likely will be critical side effects.

The application **should work stably**, and not fall with every unexpected change.

**Comment by d3lm** [comment]
There's an open [PR](https://github.com/ReactiveX/rxjs/pull/4059) that adds an option to `shareReplay` but it is still open and not merged yet. I think I would agree that in most cases you'd want to unsubscribe from the source when the ref count goes from 1 to 0. But as Kwinten said, that really depends on the use case and to be on the safe side it's a good idea to use `publishReplay` and `refCount`. As long as there is no option to enable this behavior we should advocate the safer option here.

**Comment by d3lm** [comment]
The [PR](https://github.com/ReactiveX/rxjs/pull/4059) was merged. `shareReplay` now accepts a config object. More specifically, the option `refCount` can be used to control the behavior. If you set the following config `{ refCount: true }` then the subscription to the source is reference counted. By default it's not. We should definitely mention this.

**Comment by KwintenP** [comment]
I'll update this asap with the `refCount` and a link to the `publishReplay(1).refCount()`

**Comment by d3lm** [comment]
@thekiba Would you like to change this PR to the latest API of `shareReplay` to avoid possible memory leaks with `shareReplay(1)`. Now that this [PR](https://github.com/ReactiveX/rxjs/pull/4059) was merged, I think we can change it.

**Comment by thekiba** [comment]
@d3lm Thanks for, I can.

But what do you think about that? https://github.com/ReactiveX/rxjs/issues/4530
`shareReplay` still has different behavior with `publishReplay` and `refCount`.

**Comment by d3lm** [comment]
Thanks for changing your PR. I think that what's discussed in the [issue](https://github.com/ReactiveX/rxjs/issues/4530) you mentioned is for this checklist item negligible because `shareReplay`, with the new config option, doesn't cause memory leaks anymore. The point of discussion in that issue is that it still doesn't behave the same way as `publishReplay().refCount()` but that is by design, to make `shareReplay` and other variants such as `share` retryable as opposed to the solution with `publishReplay`.

I think we can merge this one.

@KwintenP What do you say?

**Comment by KwintenP** [comment]
SGTM. Thanks for your addition!

**Pull request merged**
