### PR TITLE
fix(app/checklist) fix typos in selectors

### PR DESCRIPTION
**Pull request by geromegrignon**
Fix getFavroitesFilter to FavoritesFilter
Fix CategroriesFilter to CategoriesFilter

### CODE REVIEW

**Comment by d3lm** [comment]
Thanks for the PR @geromegrignon! I didn't really notice the typos in the selectors. Before merging this I'd like to change the commit scope to `app/checklist` and also update the the commit subject to something like `fix typos in selectors`.

For our commit messages we want to stay close to what is mentioned [here](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) on good commit messages. One important note is that we want to use the imperative mood in the subject line. For example: "Fix bug" and not "Fixed bug" or "Fixes bug."

For the scope we use `app` and `content`, but `app` can further be extended with a specific feature like `projects` or `checklist`.

Other than that it looks good to me.

**Comment by d3lm** [comment]
@geromegrignon Thanks for changing the tile of your PR. Do you mind changing your commit too? If you need help with that, please don't hesitate to let me know. You basically have to run an interactive rebase and rename your commit. Let me know if I can help you with that.

**Comment by d3lm** [comment]
@geromegrignon Any updates on this? I would really love to merge this and get the typos out of the codebase.

**Comment by geromegrignon** [comment]
@d3lm Sorry for the delay, i just found time to edit the pull request yesterday.
I fixed the commit message.

**Comment by d3lm** [comment]
No worries! I just wanted to check back on you and if you needed provide assistance.

**Comment by d3lm** [comment]
I have one last nit-pick: Do you mind changing the commit message to `fix typos in selectors`? Promised, this was the last one. Once the commit message is correct, I'll finally merge this one.

**Comment by geromegrignon** [comment]
Done!

**Comment by geromegrignon** [comment]
I appreciate your feedback as it makes me practise and improve myself!

**Comment by d3lm** [comment]
@geromegrignon Awesome, we are almost there! There is now a colon missing, like `fix(app/checklist): fix typos in selectors`. Sorry, that was my bad! I was missing the colon in my previous comment as well.

I've got a quick question, how do you commit your changes? Do you somehow bypass the commit-lint and the commit hooks? Because we actually have commit-lint that should prevent unformatted commit messages or commit headers without a type (error) or no scope (warning). I am just curious, because maybe there is something not working properly with the commit hooks.

If that's the case I have to investigate what's going on there.

**Comment by geromegrignon** [comment]
I fixed it.
I passed the commitlint successfully on the first ever commit on the project (for this pull request) but had problems of the further ones even if the messages seems right for me.

Here is an example with the addidtion of the colon.
image

I added --no-verify to skip them.
I'll avoid for the next ones and will send you the error cases.

**Comment by d3lm** [comment]
@geromegrignon Haha, now you have the colon but you are back to your old commit message :laughing: 

Please use the following, and double check if everything is correct: `fix(app/checklist): fix typos in selectors`

**Comment by d3lm** [comment]
Oh ok! I was already wondering why commit-lint was not complaining about the missing scope. That should actually raise an error. The scope is optional though.

**Comment by geromegrignon** [comment]
I still have the problem as the screenshot is from the last correction.
As "fix is declared in the "type-enum" of the commitlint file, i still don't understand the type error message (or is it more related to the body rather than the header?)

**Comment by d3lm** [comment]
Ok that is strange... I'll have a look and see if I can reproduce it on my machine.

Do you mind updating the commit message once more, and change `of` to `in`? Then we are all good, hehe.

So the commit message should be `fix(app/checklist): fix typos in selectors`

**Pull request merged**
